### ISSUE TITLE
Performance issues with the compile itself

### ISSUE THREAD

**Issue by maxkahnt** [propjockey/aug-compile#2]
I have a page that exhibits about 60 augmented elements.
If I enable `aug-compile` (using `augCompileEl`), loading that portion freezes the GUI for about 4 seconds which seems unreasonably high to me, in particular because it renders (with minor delay) and scrolls just fine without `aug-compile`.

I am using react. I feel a bit stuck as I have no idea how to investigate the excessive cpu usage.

As it comes down to three distinct augmentation shapes each of which comes with a fixed set of widths, I considered rendering a finite set of invisible augmented shapes to determine the clip-paths and then map these to my actual elements, but this is quite some effort to get done correctly dynamically for not even knowing if it will solve my issue.

Using a timeout before triggering the compilation reassured me that it is this very step that is causing the blocking.
I tried to implement my own version using `requestAnimationFrame`, `requestIdleCallback` with `augCompileElSync`, but to no avail. I would be happy for any pointers, in particular some consent that the compilation itself should neither be blocking nor expensive, given that the uncompiled rendered clip-path's are smoothly scrollable.

**Comment by JaneOri** [comment]
getComputedStyle is slow but it's not that slow. `augCompileAllSync("[data-augmented-ui]")` runs in **~416 ms** for the **274** augmented elements+psuedos on the augmented-ui homepage

It seems impossible that it's only running once for 60 elements and taking 4 entire seconds...

Can you confirm it's only running once per element? If it is, can you reproduce it in a jsbin/codepen/etc and provide that, please?

**Comment by maxkahnt** [comment]
Just an intermediate response: My priorities have to shift for some time. This is a mere note to myself at that matter.

I tried to double-check that it's running only once per element. I could not reproduce it with manually creating that amount of elements in codepen. I could not ad-hoc create a static copy of my react output. It seems pretty obvious that I am doing something wrong, but I yet cannot pinpoint what it could be.

I'm glad to read what you wrote as it meets my expectations.
